export const PERMISSIONS: Record<string, { label: string; scope: string; group: string }> = {
  'users.view':         { label: 'Kullanıcı Görüntüleme', scope: 'GLOBAL', group: 'Kullanıcılar' },
  'users.create':       { label: 'Kullanıcı Oluşturma', scope: 'GLOBAL', group: 'Kullanıcılar' },
  'users.edit':         { label: 'Kullanıcı Düzenleme', scope: 'GLOBAL', group: 'Kullanıcılar' },
  'users.delete':       { label: 'Kullanıcı Silme', scope: 'GLOBAL', group: 'Kullanıcılar' },
  'projects.view':      { label: 'Proje Görüntüleme', scope: 'GLOBAL', group: 'Projeler' },
  'projects.view_all':  { label: 'Tüm Projeleri Görme', scope: 'GLOBAL', group: 'Projeler' },
  'projects.create':    { label: 'Proje Oluşturma', scope: 'GLOBAL', group: 'Projeler' },
  'projects.edit':      { label: 'Proje Düzenleme', scope: 'GLOBAL', group: 'Projeler' },
  'projects.delete':    { label: 'Proje Silme', scope: 'GLOBAL', group: 'Projeler' },
  'reports.global':     { label: 'Global Raporlar', scope: 'GLOBAL', group: 'Raporlar' },
  'tickets.view':       { label: 'Ticket Görüntüleme', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.create':     { label: 'Ticket Oluşturma', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.edit':       { label: 'Ticket Düzenleme', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.close':      { label: 'Ticket Kapatma', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.reopen':     { label: 'Ticket Yeniden Açma', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.forward':    { label: 'Ticket Yönlendirme', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.transfer':   { label: 'Ticket Transfer', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.split':      { label: 'Ticket Bölme', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.merge':      { label: 'Ticket Birleştirme', scope: 'PROJECT', group: 'Ticketlar' },
  'tickets.assign':     { label: 'Ticket Atama', scope: 'PROJECT', group: 'Ticketlar' },
  'messages.reply':     { label: 'Müşteriye Yanıt', scope: 'PROJECT', group: 'Mesajlar' },
  'messages.internal':  { label: 'İç Not', scope: 'PROJECT', group: 'Mesajlar' },
  'messages.external':  { label: 'Dış Partner Maili', scope: 'PROJECT', group: 'Mesajlar' },
  'customers.view':     { label: 'Müşteri Görüntüleme', scope: 'PROJECT', group: 'Müşteriler' },
  'customers.edit':     { label: 'Müşteri Düzenleme', scope: 'PROJECT', group: 'Müşteriler' },
  'customers.vip':      { label: 'VIP İşaretleme', scope: 'PROJECT', group: 'Müşteriler' },
  'resolutions.add':    { label: 'Çözüm Seti Ekleme', scope: 'PROJECT', group: 'Çözüm Seti' },
  'resolutions.delete': { label: 'Çözüm Seti Silme', scope: 'PROJECT', group: 'Çözüm Seti' },
  'resolutions.approve':{ label: 'Çözüm Seti Onaylama', scope: 'PROJECT', group: 'Çözüm Seti' },
  'approvals.request':  { label: 'Onay Talebi Oluşturma', scope: 'PROJECT', group: 'Onaylar' },
  'approvals.resolve':  { label: 'Onay Verme/Reddetme', scope: 'PROJECT', group: 'Onaylar' },
  'reports.project':    { label: 'Proje Raporları', scope: 'PROJECT', group: 'Raporlar' },
  'reports.export':     { label: 'Rapor Dışa Aktarma', scope: 'PROJECT', group: 'Raporlar' },
  'settings.general':   { label: 'Genel Ayarlar', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.categories':{ label: 'Kategoriler', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.custom_fields': { label: 'Özel Alanlar', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.resolution_types': { label: 'Çözüm Türleri', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.departments': { label: 'Departmanlar', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.mail':      { label: 'Mail Ayarları', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.statuses':  { label: 'Statüler', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.sla':       { label: 'SLA Kuralları', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.users':     { label: 'Proje Üyeleri', scope: 'PROJECT', group: 'Ayarlar' },
  'settings.roles':     { label: 'Proje Rolleri', scope: 'PROJECT', group: 'Ayarlar' },
};

export const PERMISSION_GROUPS = [...new Set(Object.values(PERMISSIONS).map(p => p.group))];
